### ISSUE TITLE
Use browser-based Dropbox APIs

### ISSUE THREAD

**Issue by TimothyGu** [LilyBin/LilyBin#25]
The current Dropbox integration doesn't work:

```
curl http://localhost:3001/dropbox_login
TypeError: object is not a function
   at /home/timothy_gu/LilyBin/server.js:93:49
   at Layer.handle [as handle_request] (/home/timothy_gu/LilyBin/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/timothy_gu/LilyBin/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/home/timothy_gu/LilyBin/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/home/timothy_gu/LilyBin/node_modules/express/lib/router/layer.js:82:5)
   at /home/timothy_gu/LilyBin/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/home/timothy_gu/LilyBin/node_modules/express/lib/router/index.js:321:12)
   at next (/home/timothy_gu/LilyBin/node_modules/express/lib/router/index.js:261:10)
   at /home/timothy_gu/LilyBin/node_modules/express-session/index.js:433:7
   at /home/timothy_gu/LilyBin/node_modules/connect-mongo/lib/connect-mongo.js:305:11
```

It might be easier to just use the [Dropbox Drop-ins API](https://www.dropbox.com/developers/dropins), which eliminates all the session stuff.

**Comment by TimothyGu** [comment]
(Line numbers might be off as this is on my WIP branch, but this is also observable with c7e9ee3a32d21da111bcfc99f6f5f93bec3ff219.

**Comment by trevordixon** [comment]
Are you running it with valid DBOX_KEY and DBOX_SECRET environment variables? If not, that might be the problem (but it might be broken anyway).

In any case, those in-browser APIs are much preferable. Let's do that.

**Comment by TimothyGu** [comment]
> Are you running it with valid DBOX_KEY and DBOX_SECRET environment variables? If not, that might be the problem (but it might be broken anyway).

Yes.

In my console:

```
> require('dropbox')
{ DropboxClient: [Function] }
```

But in server.js:

```js
var DropboxClient = require('dropbox')
[…]
        var dropbox = dropboxClients[req.sessionID] = new DropboxClient({
            consumerKey: consumerKey,
            consumerSecret: consumerSecret,
            sandbox: true
        });
```

It doesn't look correct anyway.
